// Complete dataset of world countries with ISO 2-letter codes and names
const COUNTRIES_DATA = [
  { code: "af", name: "Afghanistan", continent: "Asia" },
  { code: "al", name: "Albania", continent: "Europe" },
  { code: "dz", name: "Algeria", continent: "Africa" },
  { code: "ad", name: "Andorra", continent: "Europe" },
  { code: "ao", name: "Angola", continent: "Africa" },
  { code: "ag", name: "Antigua & Barbuda", continent: "Americas" },
  { code: "ar", name: "Argentina", continent: "Americas" },
  { code: "am", name: "Armenia", continent: "Asia" },
  { code: "au", name: "Australia", continent: "Oceania" },
  { code: "at", name: "Austria", continent: "Europe" },
  { code: "az", name: "Azerbaijan", continent: "Asia" },
  { code: "bs", name: "Bahamas", continent: "Americas" },
  { code: "bh", name: "Bahrain", continent: "Asia" },
  { code: "bd", name: "Bangladesh", continent: "Asia" },
  { code: "bb", name: "Barbados", continent: "Americas" },
  { code: "by", name: "Belarus", continent: "Europe" },
  { code: "be", name: "Belgium", continent: "Europe" },
  { code: "bz", name: "Belize", continent: "Americas" },
  { code: "bj", name: "Benin", continent: "Africa" },
  { code: "bt", name: "Bhutan", continent: "Asia" },
  { code: "bo", name: "Bolivia", continent: "Americas" },
  { code: "ba", name: "Bosnia & Herzegovina", continent: "Europe" },
  { code: "bw", name: "Botswana", continent: "Africa" },
  { code: "br", name: "Brazil", continent: "Americas" },
  { code: "bn", name: "Brunei", continent: "Asia" },
  { code: "bg", name: "Bulgaria", continent: "Europe" },
  { code: "bf", name: "Burkina Faso", continent: "Africa" },
  { code: "bi", name: "Burundi", continent: "Africa" },
  { code: "cv", name: "Cabo Verde", continent: "Africa" },
  { code: "kh", name: "Cambodia", continent: "Asia" },
  { code: "cm", name: "Cameroon", continent: "Africa" },
  { code: "ca", name: "Canada", continent: "Americas" },
  { code: "cf", name: "Central African Rep.", continent: "Africa" },
  { code: "td", name: "Chad", continent: "Africa" },
  { code: "cl", name: "Chile", continent: "Americas" },
  { code: "cn", name: "China", continent: "Asia" },
  { code: "co", name: "Colombia", continent: "Americas" },
  { code: "km", name: "Comoros", continent: "Africa" },
  { code: "cd", name: "DR Congo", continent: "Africa" },
  { code: "cg", name: "Congo", continent: "Africa" },
  { code: "cr", name: "Costa Rica", continent: "Americas" },
  { code: "hr", name: "Croatia", continent: "Europe" },
  { code: "cu", name: "Cuba", continent: "Americas" },
  { code: "cy", name: "Cyprus", continent: "Europe" },
  { code: "cz", name: "Czechia", continent: "Europe" },
  { code: "dk", name: "Denmark", continent: "Europe" },
  { code: "dj", name: "Djibouti", continent: "Africa" },
  { code: "dm", name: "Dominica", continent: "Americas" },
  { code: "do", name: "Dominican Rep.", continent: "Americas" },
  { code: "ec", name: "Ecuador", continent: "Americas" },
  { code: "eg", name: "Egypt", continent: "Africa" },
  { code: "sv", name: "El Salvador", continent: "Americas" },
  { code: "gq", name: "Equatorial Guinea", continent: "Africa" },
  { code: "er", name: "Eritrea", continent: "Africa" },
  { code: "ee", name: "Estonia", continent: "Europe" },
  { code: "sz", name: "Eswatini", continent: "Africa" },
  { code: "et", name: "Ethiopia", continent: "Africa" },
  { code: "fj", name: "Fiji", continent: "Oceania" },
  { code: "fi", name: "Finland", continent: "Europe" },
  { code: "fr", name: "France", continent: "Europe" },
  { code: "ga", name: "Gabon", continent: "Africa" },
  { code: "gm", name: "Gambia", continent: "Africa" },
  { code: "ge", name: "Georgia", continent: "Asia" },
  { code: "de", name: "Germany", continent: "Europe" },
  { code: "gh", name: "Ghana", continent: "Africa" },
  { code: "gr", name: "Greece", continent: "Europe" },
  { code: "gd", name: "Grenada", continent: "Americas" },
  { code: "gt", name: "Guatemala", continent: "Americas" },
  { code: "gn", name: "Guinea", continent: "Africa" },
  { code: "gw", name: "Guinea-Bissau", continent: "Africa" },
  { code: "gy", name: "Guyana", continent: "Americas" },
  { code: "ht", name: "Haiti", continent: "Americas" },
  { code: "hn", name: "Honduras", continent: "Americas" },
  { code: "hu", name: "Hungary", continent: "Europe" },
  { code: "is", name: "Iceland", continent: "Europe" },
  { code: "in", name: "India", continent: "Asia" },
  { code: "id", name: "Indonesia", continent: "Asia" },
  { code: "ir", name: "Iran", continent: "Asia" },
  { code: "iq", name: "Iraq", continent: "Asia" },
  { code: "ie", name: "Ireland", continent: "Europe" },
  { code: "il", name: "Israel", continent: "Asia" },
  { code: "it", name: "Italy", continent: "Europe" },
  { code: "ci", name: "Ivory Coast", continent: "Africa" },
  { code: "jm", name: "Jamaica", continent: "Americas" },
  { code: "jp", name: "Japan", continent: "Asia" },
  { code: "jo", name: "Jordan", continent: "Asia" },
  { code: "kz", name: "Kazakhstan", continent: "Asia" },
  { code: "ke", name: "Kenya", continent: "Africa" },
  { code: "ki", name: "Kiribati", continent: "Oceania" },
  { code: "kp", name: "North Korea", continent: "Asia" },
  { code: "kr", name: "South Korea", continent: "Asia" },
  { code: "kw", name: "Kuwait", continent: "Asia" },
  { code: "kg", name: "Kyrgyzstan", continent: "Asia" },
  { code: "la", name: "Laos", continent: "Asia" },
  { code: "lv", name: "Latvia", continent: "Europe" },
  { code: "lb", name: "Lebanon", continent: "Asia" },
  { code: "ls", name: "Lesotho", continent: "Africa" },
  { code: "lr", name: "Liberia", continent: "Africa" },
  { code: "ly", name: "Libya", continent: "Africa" },
  { code: "li", name: "Liechtenstein", continent: "Europe" },
  { code: "lt", name: "Lithuania", continent: "Europe" },
  { code: "lu", name: "Luxembourg", continent: "Europe" },
  { code: "mg", name: "Madagascar", continent: "Africa" },
  { code: "mw", name: "Malawi", continent: "Africa" },
  { code: "my", name: "Malaysia", continent: "Asia" },
  { code: "mv", name: "Maldives", continent: "Asia" },
  { code: "ml", name: "Mali", continent: "Africa" },
  { code: "mt", name: "Malta", continent: "Europe" },
  { code: "mh", name: "Marshall Islands", continent: "Oceania" },
  { code: "mr", name: "Mauritania", continent: "Africa" },
  { code: "mu", name: "Mauritius", continent: "Africa" },
  { code: "mx", name: "Mexico", continent: "Americas" },
  { code: "fm", name: "Micronesia", continent: "Oceania" },
  { code: "md", name: "Moldova", continent: "Europe" },
  { code: "mc", name: "Monaco", continent: "Europe" },
  { code: "mn", name: "Mongolia", continent: "Asia" },
  { code: "me", name: "Montenegro", continent: "Europe" },
  { code: "ma", name: "Morocco", continent: "Africa" },
  { code: "mz", name: "Mozambique", continent: "Africa" },
  { code: "mm", name: "Myanmar", continent: "Asia" },
  { code: "na", name: "Namibia", continent: "Africa" },
  { code: "nr", name: "Nauru", continent: "Oceania" },
  { code: "np", name: "Nepal", continent: "Asia" },
  { code: "nl", name: "Netherlands", continent: "Europe" },
  { code: "nz", name: "New Zealand", continent: "Oceania" },
  { code: "ni", name: "Nicaragua", continent: "Americas" },
  { code: "ne", name: "Niger", continent: "Africa" },
  { code: "ng", name: "Nigeria", continent: "Africa" },
  { code: "mk", name: "North Macedonia", continent: "Europe" },
  { code: "no", name: "Norway", continent: "Europe" },
  { code: "om", name: "Oman", continent: "Asia" },
  { code: "pk", name: "Pakistan", continent: "Asia" },
  { code: "pw", name: "Palau", continent: "Oceania" },
  { code: "ps", name: "Palestine", continent: "Asia" },
  { code: "pa", name: "Panama", continent: "Americas" },
  { code: "pg", name: "Papua New Guinea", continent: "Oceania" },
  { code: "py", name: "Paraguay", continent: "Americas" },
  { code: "pe", name: "Peru", continent: "Americas" },
  { code: "ph", name: "Philippines", continent: "Asia" },
  { code: "pl", name: "Poland", continent: "Europe" },
  { code: "pt", name: "Portugal", continent: "Europe" },
  { code: "qa", name: "Qatar", continent: "Asia" },
  { code: "ro", name: "Romania", continent: "Europe" },
  { code: "ru", name: "Russia", continent: "Europe" },
  { code: "rw", name: "Rwanda", continent: "Africa" },
  { code: "kn", name: "St. Kitts & Nevis", continent: "Americas" },
  { code: "lc", name: "St. Lucia", continent: "Americas" },
  { code: "vc", name: "St. Vincent", continent: "Americas" },
  { code: "ws", name: "Samoa", continent: "Oceania" },
  { code: "sm", name: "San Marino", continent: "Europe" },
  { code: "st", name: "Sao Tome", continent: "Africa" },
  { code: "sa", name: "Saudi Arabia", continent: "Asia" },
  { code: "sn", name: "Senegal", continent: "Africa" },
  { code: "rs", name: "Serbia", continent: "Europe" },
  { code: "sc", name: "Seychelles", continent: "Africa" },
  { code: "sl", name: "Sierra Leone", continent: "Africa" },
  { code: "sg", name: "Singapore", continent: "Asia" },
  { code: "sk", name: "Slovakia", continent: "Europe" },
  { code: "si", name: "Slovenia", continent: "Europe" },
  { code: "sb", name: "Solomon Islands", continent: "Oceania" },
  { code: "so", name: "Somalia", continent: "Africa" },
  { code: "za", name: "South Africa", continent: "Africa" },
  { code: "ss", name: "South Sudan", continent: "Africa" },
  { code: "es", name: "Spain", continent: "Europe" },
  { code: "lk", name: "Sri Lanka", continent: "Asia" },
  { code: "sd", name: "Sudan", continent: "Africa" },
  { code: "sr", name: "Suriname", continent: "Americas" },
  { code: "se", name: "Sweden", continent: "Europe" },
  { code: "ch", name: "Switzerland", continent: "Europe" },
  { code: "sy", name: "Syria", continent: "Asia" },
  { code: "tw", name: "Taiwan", continent: "Asia" },
  { code: "tj", name: "Tajikistan", continent: "Asia" },
  { code: "tz", name: "Tanzania", continent: "Africa" },
  { code: "th", name: "Thailand", continent: "Asia" },
  { code: "tl", name: "Timor-Leste", continent: "Asia" },
  { code: "tg", name: "Togo", continent: "Africa" },
  { code: "to", name: "Tonga", continent: "Oceania" },
  { code: "tt", name: "Trinidad & Tobago", continent: "Americas" },
  { code: "tn", name: "Tunisia", continent: "Africa" },
  { code: "tr", name: "Turkey", continent: "Asia" },
  { code: "tm", name: "Turkmenistan", continent: "Asia" },
  { code: "tv", name: "Tuvalu", continent: "Oceania" },
  { code: "ug", name: "Uganda", continent: "Africa" },
  { code: "ua", name: "Ukraine", continent: "Europe" },
  { code: "ae", name: "UAE", continent: "Asia" },
  { code: "gb", name: "United Kingdom", continent: "Europe" },
  { code: "us", name: "United States", continent: "Americas" },
  { code: "uy", name: "Uruguay", continent: "Americas" },
  { code: "uz", name: "Uzbekistan", continent: "Asia" },
  { code: "vu", name: "Vanuatu", continent: "Oceania" },
  { code: "va", name: "Vatican City", continent: "Europe" },
  { code: "ve", name: "Venezuela", continent: "Americas" },
  { code: "vn", name: "Vietnam", continent: "Asia" },
  { code: "ye", name: "Yemen", continent: "Asia" },
  { code: "zm", name: "Zambia", continent: "Africa" },
  { code: "zw", name: "Zimbabwe", continent: "Africa" }
];

// Reliable flag thumbnail provider
function getFlagUrl(code) {
  return `https://flagcdn.com/w160/${code.toLowerCase()}.png`;
}
